#!/usr/bin/env node
/**
 * Generates a static CSS file exposing Aether design tokens as CSS custom
 * properties, following the user's OS color scheme automatically:
 *
 *   :root { ...light tokens... }
 *   @media (prefers-color-scheme: dark) { :root { ...dark tokens... } }
 *
 * Running this at build time means the app source never imports any @postman/*
 * package directly — it just consumes the generated CSS variables.
 */
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import fs from 'node:fs';

const require = createRequire(import.meta.url);
const { light, dark } = require('@postman/aether-design-tokens');

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT_DIR = path.join(__dirname, '..', 'src', 'generated');
const OUT_FILE = path.join(OUT_DIR, 'aether-theme.css');

// Metadata keys on the theme object that aren't design tokens.
const META_KEYS = new Set(['name', 'colorScheme']);

/** @param {Record<string, unknown>} tokens */
function toDeclarations(tokens) {
  return Object.entries(tokens)
    .filter(([key, value]) => !META_KEYS.has(key) && (typeof value === 'string' || typeof value === 'number'))
    .map(([name, value]) => `  --${name}: ${String(value)};`)
    .join('\n');
}

function main() {
  fs.mkdirSync(OUT_DIR, { recursive: true });

  const css = [
    '/* AUTO-GENERATED by scripts/generate-theme.mjs — do not edit by hand. */',
    ':root {',
    '  color-scheme: light;',
    toDeclarations(light),
    '}',
    '',
    '@media (prefers-color-scheme: dark) {',
    '  :root {',
    '    color-scheme: dark;',
    toDeclarations(dark)
      .split('\n')
      .map((line) => `  ${line}`)
      .join('\n'),
    '  }',
    '}',
    '',
  ].join('\n');

  fs.writeFileSync(OUT_FILE, css);
  console.info('Generated %s', path.relative(path.join(__dirname, '..'), OUT_FILE));
}

main();
